# Generated by Django 4.1.2 on 2022-12-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionagence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionagence',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gestionagence',
            name='email',
        ),
        migrations.AddField(
            model_name='gestionagence',
            name='siege',
            field=models.CharField(default='Yaounde', max_length=30),
        ),
        migrations.AddField(
            model_name='gestionagence',
            name='telephone',
            field=models.CharField(default='678963685', max_length=30),
        ),
        migrations.AlterField(
            model_name='gestionagence',
            name='description',
            field=models.TextField(default='Description de l agence '),
        ),
    ]
