# Generated by Django 4.1.2 on 2022-12-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionagence', '0002_remove_gestionagence_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionagence',
            name='description',
            field=models.CharField(default='Description de l agence ', max_length=30),
        ),
    ]
