# Generated by Django 4.1.2 on 2023-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionagence', '0004_userregisterform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBus', models.CharField(max_length=50)),
                ('typeBus', models.CharField(default='Yaounde', max_length=30)),
                ('nombrePlace', models.IntegerField()),
                ('nombrePlaceDispo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idQuartier', models.CharField(max_length=50)),
                ('nomQuartier', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idVille', models.CharField(max_length=50)),
                ('nomVille', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idVoyage', models.CharField(max_length=50)),
                ('lieuDepart', models.CharField(default='Yaounde', max_length=30)),
                ('lieuArriver', models.CharField(default='678963685', max_length=30)),
                ('heureDepart', models.TimeField()),
                ('heureArriver', models.TimeField()),
            ],
        ),
    ]
