# Generated by Django 4.1.2 on 2022-12-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crud',
        ),
    ]
