# Generated by Django 4.1.2 on 2023-01-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gestionagence',
            new_name='UserRegisterform',
        ),
    ]
