# Generated by Django 4.1.2 on 2023-01-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionagence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('siege', models.CharField(default='Yaounde', max_length=30)),
                ('telephone', models.CharField(default='678963685', max_length=30)),
                ('description', models.CharField(default='Description de l agence ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(choices=[('yaounde', 'yaounde'), ('douala', 'douala'), ('bafoussam', 'bafoussam'), ('dschang', 'dschang'), ('buea', 'buea')], default='lieu de depart', max_length=30)),
                ('destination', models.CharField(choices=[('douala', 'douala'), ('yaounde', 'yaounde'), ('bafoussam', 'bafoussam'), ('dschang', 'dschang'), ('buea', 'buea')], default='lieu de destination', max_length=30)),
                ('datedepart', models.DateField(default='date de depart')),
                ('qte', models.IntegerField(default='nombre de place')),
            ],
        ),
    ]
