# Generated by Django 4.1.2 on 2023-01-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gestionagence',
        ),
    ]
