# Generated by Django 4.1.2 on 2023-01-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservationcreate_delete_reservationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationcreate',
            name='depart',
            field=models.CharField(choices=[('yaounde', 'yaounde'), ('douala', 'douala'), ('bafoussam', 'bafoussam'), ('dschang', 'dschang'), ('buea', 'buea')], max_length=30),
        ),
    ]
